name: ttmnky
favicon: null
layout_spectrum: 0.50077
typography_spectrum: 0.5326008908450603
title: Turntable Monkey
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#666666'
    - '#081620'
    - '#3399cc'
    - '#8b3600'
  brandStrength: 0.2595205963589251
  lightness: 0.1057710936293006
  saturation: 0.6004912175703794
  rhythmicContrast: 0.5845638662576675
purpose: []
